on:
  push:
    branches:
      - master
  pull_request:
    branches: '*'

name: Project check
jobs:
  set-up:
    name: Linting
    runs-on: ubuntu-latest
    steps:
    - name: Checkout ğŸ›ï¸
      uses: actions/checkout@v3

    - name: Package manager
      uses: pnpm/action-setup@v2
      with:
        version: 7
        
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        cache: 'pnpm'
        
    - run: node -v
    - run: pnpm -v
        
    - name: Install dependencies ğŸ“¦
      run: pnpm i --frozen-lockfile





# linting:
#   name: Linting ğŸ§¹
#   runs-on: ubuntu-latest
#   needs: set-up
#   steps:
#   - run: pnpm lint

# test:
#   name: Test ğŸ§ª
#   runs-on: ubuntu-latest
#   needs: set-up
#   steps:
#   - run: pnpm test:once

# deploy:
#   name: Build & Deploy
#   runs-on: ubuntu-latest
#   needs: set-up
#   steps:
#   - name: build ğŸ—
#     run: |
#       pnpm build

#   - name: Deploy ğŸš€
#     uses: JamesIves/github-pages-deploy-action@v4
#     with:
#       folder: build
#       branch: deploy
